/*****************************************************************************
 * File generated by HDevelop for HALCON/C Version 19.05.0.0
 * Non-ASCII strings in this file are encoded in UTF-8.
 * 
 * Please note that non-ASCII characters in string constants are exported
 * as octal codes in order to guarantee that the strings are correctly
 * created on all systems, independent on any compiler settings.
 * 
 * Source files with different encoding should not be mixed in one project.
 *****************************************************************************/




#ifndef __APPLE__
#  include "HalconC.h"
#  include "halconc/Hdevthread.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONC/HalconC.h>
#    include <HALCONC/Hdevthread.h>
#  else
#    include <HALCONCxl/HalconC.h>
#    include <HALCONCxl/Hdevthread.h>
#  endif
#endif



/* Chapter: Graphics / Text*/
/* Short Description: Set font independent of OS */
void set_display_font (Htuple hv_WindowHandle, Htuple hv_Size, Htuple hv_Font, Htuple hv_Bold, 
    Htuple hv_Slant)
{

  /* Stack for temporary tuples */
  Htuple   TTemp[100];
  int      SP=0;
  /* Stack for temporary tuple vectors */
  Hvector  TVTemp[100] = {0};
  int      SPTV=0;

  /* Local iconic variables */

  /* Local control variables */
  Htuple  hv_OS, hv_Fonts, hv_Style, hv_Exception;
  Htuple  hv_AvailableFonts, hv_Fdx, hv_Indices;

  /* Local copy input parameter variables */
  Htuple   hv_Font_COPY_INP_TMP;
  Htuple   hv_Size_COPY_INP_TMP;


  /* Initialize control variables */
  create_tuple(&hv_OS,0);
  create_tuple(&hv_Fonts,0);
  create_tuple(&hv_Style,0);
  create_tuple(&hv_Exception,0);
  create_tuple(&hv_AvailableFonts,0);
  create_tuple(&hv_Fdx,0);
  create_tuple(&hv_Indices,0);
  copy_tuple(hv_Font,&hv_Font_COPY_INP_TMP);
  copy_tuple(hv_Size,&hv_Size_COPY_INP_TMP);

  /****************************************************/
  /******************   Begin procedure   *************/
  /****************************************************/

  /*This procedure sets the text font of the current window with*/
  /*the specified attributes.*/
  /**/
  /*Input parameters:*/
  /*WindowHandle: The graphics window for which the font will be set*/
  /*Size: The font size. If Size=-1, the default of 16 is used.*/
  /*Bold: If set to 'true', a bold font is used*/
  /*Slant: If set to 'true', a slanted font is used*/
  /**/
  /*get_system ('operating_system', OS)*/
  create_tuple_s(&TTemp[SP++],"operating_system");
  destroy_tuple(hv_OS);
  /***/T_get_system(TTemp[SP-1], &hv_OS);
  destroy_tuple(TTemp[--SP]);

  /*========== if (Size == [] or Size == -1) ==========*/
  create_tuple(&TTemp[SP++],0);
  T_tuple_equal(hv_Size_COPY_INP_TMP,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  create_tuple_i(&TTemp[SP++],-1);
  T_tuple_equal(hv_Size_COPY_INP_TMP,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  T_tuple_or(TTemp[SP-2],TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-2]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-2]=TTemp[SP];
  SP=SP-1;
  if(get_i(TTemp[SP-1],0))
  {
    /*Size := 16*/
    reuse_tuple_i(&hv_Size_COPY_INP_TMP,16);

  }
  destroy_tuple(TTemp[--SP]);
  /*========== end if ==========*/
  /*========== if (OS{0:2} == 'Win') ==========*/
  create_tuple_i(&TTemp[SP++],0);
  create_tuple_i(&TTemp[SP++],2);
  T_tuple_substr(hv_OS,TTemp[SP-2],TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-2]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-2]=TTemp[SP];
  SP=SP-1;
  create_tuple_s(&TTemp[SP++],"Win");
  T_tuple_equal(TTemp[SP-2],TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-2]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-2]=TTemp[SP];
  SP=SP-1;
  if(get_i(TTemp[SP-1],0))
  {
    /*Restore previous behaviour*/
    /*Size := int(1.13677 * Size)*/
    create_tuple_d(&TTemp[SP++],1.13677);
    copy_tuple(hv_Size_COPY_INP_TMP,&TTemp[SP++]);
    T_tuple_mult(TTemp[SP-2],TTemp[SP-1],&TTemp[SP]);
    destroy_tuple(TTemp[SP-2]);
    destroy_tuple(TTemp[SP-1]);
    TTemp[SP-2]=TTemp[SP];
    SP=SP-1;
    T_tuple_int(TTemp[SP-1],&TTemp[SP]);
    destroy_tuple(TTemp[SP-1]);
    TTemp[SP-1]=TTemp[SP];
    destroy_tuple(hv_Size_COPY_INP_TMP);
    hv_Size_COPY_INP_TMP=TTemp[--SP];

  }
  else
  {
    /*Size := int(Size)*/
    copy_tuple(hv_Size_COPY_INP_TMP,&TTemp[SP++]);
    T_tuple_int(TTemp[SP-1],&TTemp[SP]);
    destroy_tuple(TTemp[SP-1]);
    TTemp[SP-1]=TTemp[SP];
    destroy_tuple(hv_Size_COPY_INP_TMP);
    hv_Size_COPY_INP_TMP=TTemp[--SP];

  }
  destroy_tuple(TTemp[--SP]);
  /*========== end if ==========*/
  /*========== if (Font == 'Courier') ==========*/
  create_tuple_s(&TTemp[SP++],"Courier");
  T_tuple_equal(hv_Font_COPY_INP_TMP,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /*Fonts := ['Courier','Courier 10 Pitch','Courier New','CourierNew','Liberation Mono']*/
    create_tuple(&TTemp[SP++],5);
    set_s(TTemp[SP-1],"Courier",0);
    set_s(TTemp[SP-1],"Courier 10 Pitch",1);
    set_s(TTemp[SP-1],"Courier New",2);
    set_s(TTemp[SP-1],"CourierNew",3);
    set_s(TTemp[SP-1],"Liberation Mono",4);
    destroy_tuple(hv_Fonts);
    hv_Fonts=TTemp[--SP];

  }
  else
  {
  destroy_tuple(TTemp[--SP]);
  /*========== elseif (Font == 'mono') ==========*/

  create_tuple_s(&TTemp[SP++],"mono");
  T_tuple_equal(hv_Font_COPY_INP_TMP,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /*Fonts := ['Consolas','Menlo','Courier','Courier 10 Pitch','FreeMono','Liberation Mono']*/
    create_tuple(&TTemp[SP++],6);
    set_s(TTemp[SP-1],"Consolas",0);
    set_s(TTemp[SP-1],"Menlo",1);
    set_s(TTemp[SP-1],"Courier",2);
    set_s(TTemp[SP-1],"Courier 10 Pitch",3);
    set_s(TTemp[SP-1],"FreeMono",4);
    set_s(TTemp[SP-1],"Liberation Mono",5);
    destroy_tuple(hv_Fonts);
    hv_Fonts=TTemp[--SP];

  }
  else
  {
  destroy_tuple(TTemp[--SP]);
  /*========== elseif (Font == 'sans') ==========*/

  create_tuple_s(&TTemp[SP++],"sans");
  T_tuple_equal(hv_Font_COPY_INP_TMP,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /*Fonts := ['Luxi Sans','DejaVu Sans','FreeSans','Arial','Liberation Sans']*/
    create_tuple(&TTemp[SP++],5);
    set_s(TTemp[SP-1],"Luxi Sans",0);
    set_s(TTemp[SP-1],"DejaVu Sans",1);
    set_s(TTemp[SP-1],"FreeSans",2);
    set_s(TTemp[SP-1],"Arial",3);
    set_s(TTemp[SP-1],"Liberation Sans",4);
    destroy_tuple(hv_Fonts);
    hv_Fonts=TTemp[--SP];

  }
  else
  {
  destroy_tuple(TTemp[--SP]);
  /*========== elseif (Font == 'serif') ==========*/

  create_tuple_s(&TTemp[SP++],"serif");
  T_tuple_equal(hv_Font_COPY_INP_TMP,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /*Fonts := ['Times New Roman','Luxi Serif','DejaVu Serif','FreeSerif','Utopia','Liberation Serif']*/
    create_tuple(&TTemp[SP++],6);
    set_s(TTemp[SP-1],"Times New Roman",0);
    set_s(TTemp[SP-1],"Luxi Serif",1);
    set_s(TTemp[SP-1],"DejaVu Serif",2);
    set_s(TTemp[SP-1],"FreeSerif",3);
    set_s(TTemp[SP-1],"Utopia",4);
    set_s(TTemp[SP-1],"Liberation Serif",5);
    destroy_tuple(hv_Fonts);
    hv_Fonts=TTemp[--SP];

  }
  else
  {
    /*Fonts := Font*/
    destroy_tuple(hv_Fonts);
    copy_tuple(hv_Font_COPY_INP_TMP,&hv_Fonts);

  }
  }
  }
  }
  destroy_tuple(TTemp[--SP]);
  /*========== end if ==========*/
  /*Style := ''*/
  reuse_tuple_s(&hv_Style,"");
  /*========== if (Bold == 'true') ==========*/
  create_tuple_s(&TTemp[SP++],"true");
  T_tuple_equal(hv_Bold,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /*Style := Style + 'Bold'*/
    create_tuple_s(&TTemp[SP++],"Bold");
    T_tuple_add(hv_Style,TTemp[SP-1],&TTemp[SP]);
    destroy_tuple(hv_Style);
    hv_Style=TTemp[SP];
    destroy_tuple(TTemp[--SP]);

  }
  else
  {
  destroy_tuple(TTemp[--SP]);
  /*========== elseif (Bold != 'false') ==========*/

  create_tuple_s(&TTemp[SP++],"false");
  T_tuple_not_equal(hv_Bold,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /*Exception := 'Wrong value of control parameter Bold'*/
    reuse_tuple_s(&hv_Exception,"Wrong value of control parameter Bold");
    /* throw(...); only in hdevelop*/
  }
  }
  destroy_tuple(TTemp[--SP]);
  /*========== end if ==========*/
  /*========== if (Slant == 'true') ==========*/
  create_tuple_s(&TTemp[SP++],"true");
  T_tuple_equal(hv_Slant,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /*Style := Style + 'Italic'*/
    create_tuple_s(&TTemp[SP++],"Italic");
    T_tuple_add(hv_Style,TTemp[SP-1],&TTemp[SP]);
    destroy_tuple(hv_Style);
    hv_Style=TTemp[SP];
    destroy_tuple(TTemp[--SP]);

  }
  else
  {
  destroy_tuple(TTemp[--SP]);
  /*========== elseif (Slant != 'false') ==========*/

  create_tuple_s(&TTemp[SP++],"false");
  T_tuple_not_equal(hv_Slant,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /*Exception := 'Wrong value of control parameter Slant'*/
    reuse_tuple_s(&hv_Exception,"Wrong value of control parameter Slant");
    /* throw(...); only in hdevelop*/
  }
  }
  destroy_tuple(TTemp[--SP]);
  /*========== end if ==========*/
  /*========== if (Style == '') ==========*/
  create_tuple_s(&TTemp[SP++],"");
  T_tuple_equal(hv_Style,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /*Style := 'Normal'*/
    reuse_tuple_s(&hv_Style,"Normal");
  }
  destroy_tuple(TTemp[--SP]);
  /*========== end if ==========*/
  /*query_font (WindowHandle, AvailableFonts)*/
  destroy_tuple(hv_AvailableFonts);
  /***/T_query_font(hv_WindowHandle, &hv_AvailableFonts);

  /*Font := ''*/
  reuse_tuple_s(&hv_Font_COPY_INP_TMP,"");
  /*========== for Fdx := 0 to |Fonts| - 1 by 1 ==========*/
  T_tuple_length(hv_Fonts,&TTemp[SP++]);
  create_tuple_i(&TTemp[SP++],1);
  T_tuple_sub(TTemp[SP-2],TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-2]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-2]=TTemp[SP];
  SP=SP-1;
  create_tuple_i(&TTemp[SP++],1);
  create_tuple_i(&TTemp[SP++],0);
  T_tuple_greater(TTemp[SP-1],TTemp[SP-3],&TTemp[SP]);
  SP++;
  T_tuple_equal(TTemp[SP-2],TTemp[SP-4],&TTemp[SP]);
  if(get_i(TTemp[SP],0) ||
     (!((( get_i(TTemp[SP-1],0)) && (get_d(TTemp[SP-3],0)>0)) ||
        ((!get_i(TTemp[SP-1],0)) && (get_d(TTemp[SP-3],0)<0)))))
  {
   destroy_tuple(TTemp[SP--]);
   destroy_tuple(TTemp[SP]);
   T_tuple_sub(TTemp[SP-1],TTemp[SP-2],&TTemp[SP]);
   destroy_tuple(hv_Fdx);
   copy_tuple(TTemp[SP],&hv_Fdx);
   destroy_tuple(TTemp[SP--]);
   destroy_tuple(TTemp[SP]);
   for(;;)
   {
   T_tuple_add(hv_Fdx,TTemp[SP-1],&TTemp[SP]);
   destroy_tuple(hv_Fdx);
   copy_tuple(TTemp[SP],&hv_Fdx);
   destroy_tuple(TTemp[SP]);
   if(get_d(TTemp[SP-1],0)<0)
    T_tuple_less(hv_Fdx,TTemp[SP-2],&TTemp[SP]);
   else
    T_tuple_greater(hv_Fdx,TTemp[SP-2],&TTemp[SP]);
   if(get_i(TTemp[SP],0)) break;
   destroy_tuple(TTemp[SP]);
   /*========== for ==========*/

    /*Indices := find(AvailableFonts,Fonts[Fdx])*/
    T_tuple_select(hv_Fonts,hv_Fdx,&TTemp[SP++]);
    T_tuple_find(hv_AvailableFonts,TTemp[SP-1],&TTemp[SP]);
    destroy_tuple(TTemp[SP-1]);
    TTemp[SP-1]=TTemp[SP];
    destroy_tuple(hv_Indices);
    hv_Indices=TTemp[--SP];

    /*========== if (|Indices| > 0) ==========*/
    T_tuple_length(hv_Indices,&TTemp[SP++]);
    create_tuple_i(&TTemp[SP++],0);
    T_tuple_greater(TTemp[SP-2],TTemp[SP-1],&TTemp[SP]);
    destroy_tuple(TTemp[SP-2]);
    destroy_tuple(TTemp[SP-1]);
    TTemp[SP-2]=TTemp[SP];
    SP=SP-1;
    if(get_i(TTemp[SP-1],0))
    {
      /*========== if (Indices[0] >= 0) ==========*/
      create_tuple_i(&TTemp[SP++],0);
      T_tuple_select(hv_Indices,TTemp[SP-1],&TTemp[SP]);
      destroy_tuple(TTemp[SP-1]);
      TTemp[SP-1]=TTemp[SP];
      create_tuple_i(&TTemp[SP++],0);
      T_tuple_greater_equal(TTemp[SP-2],TTemp[SP-1],&TTemp[SP]);
      destroy_tuple(TTemp[SP-2]);
      destroy_tuple(TTemp[SP-1]);
      TTemp[SP-2]=TTemp[SP];
      SP=SP-1;
      if(get_i(TTemp[SP-1],0))
      {
        /*Font := Fonts[Fdx]*/
        T_tuple_select(hv_Fonts,hv_Fdx,&TTemp[SP++]);
        destroy_tuple(hv_Font_COPY_INP_TMP);
        hv_Font_COPY_INP_TMP=TTemp[--SP];

        /*break*/
        destroy_tuple(TTemp[--SP]);
        destroy_tuple(TTemp[--SP]);
        create_tuple(&TTemp[SP],0);
        break;
      }
      destroy_tuple(TTemp[--SP]);
      /*========== end if ==========*/
    }
    destroy_tuple(TTemp[--SP]);
    /*========== end if ==========*/
   }
   destroy_tuple(TTemp[SP--]);
   destroy_tuple(TTemp[SP--]);
   destroy_tuple(TTemp[SP]);
  }
  else
  {
   destroy_tuple(TTemp[SP--]);
   destroy_tuple(TTemp[SP--]);
   destroy_tuple(TTemp[SP--]);
   destroy_tuple(TTemp[SP--]);
   destroy_tuple(TTemp[SP]);
  }/*========== end for ========*/

  /*========== if (Font == '') ==========*/
  create_tuple_s(&TTemp[SP++],"");
  T_tuple_equal(hv_Font_COPY_INP_TMP,TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  if(get_i(TTemp[SP-1],0))
  {
    /* throw(...); only in hdevelop*/
  }
  destroy_tuple(TTemp[--SP]);
  /*========== end if ==========*/
  /*Font := Font + '-' + Style + '-' + Size*/
  copy_tuple(hv_Font_COPY_INP_TMP,&TTemp[SP++]);
  create_tuple_s(&TTemp[SP++],"-");
  T_tuple_add(TTemp[SP-2],TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-2]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-2]=TTemp[SP];
  SP=SP-1;
  T_tuple_add(TTemp[SP-1],hv_Style,&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  create_tuple_s(&TTemp[SP++],"-");
  T_tuple_add(TTemp[SP-2],TTemp[SP-1],&TTemp[SP]);
  destroy_tuple(TTemp[SP-2]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-2]=TTemp[SP];
  SP=SP-1;
  T_tuple_add(TTemp[SP-1],hv_Size_COPY_INP_TMP,&TTemp[SP]);
  destroy_tuple(TTemp[SP-1]);
  TTemp[SP-1]=TTemp[SP];
  destroy_tuple(hv_Font_COPY_INP_TMP);
  hv_Font_COPY_INP_TMP=TTemp[--SP];

  /*set_font (WindowHandle, Font)*/
  /***/T_set_font(hv_WindowHandle, hv_Font_COPY_INP_TMP);

  /*========== return ==========*/

  /* Clear temporary tuple stack */
  while (SP > 0)
    destroy_tuple(TTemp[--SP]);
  /* Clear temporary tuple vectors stack*/
  while (SPTV > 0)
    V_destroy_vector(TVTemp[--SPTV]);
  /* Clear local control variables */
  destroy_tuple(hv_OS);
  destroy_tuple(hv_Fonts);
  destroy_tuple(hv_Style);
  destroy_tuple(hv_Exception);
  destroy_tuple(hv_AvailableFonts);
  destroy_tuple(hv_Fdx);
  destroy_tuple(hv_Indices);
  destroy_tuple(hv_Font_COPY_INP_TMP);
  destroy_tuple(hv_Size_COPY_INP_TMP);

  return;

  /****************************************************/
  /******************     End procedure   *************/
  /****************************************************/

}
